# Generated by Django 3.0 on 2019-12-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.FileField(default='作品描述', upload_to='')),
                ('title', models.CharField(default='作品标题', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
            ],
        ),
    ]
